---
title: ZOO
timezone: UTC
email: info@zoovenues.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  ZOO returns to the Edinburgh Fringe in 2023 with a bigger and better programme than ever before.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zoofestival.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zoovenues
github_username: samozzy
keywords: Theatre, Arts, Fringe, Edinburgh, August
page_excerpts: true
dates:
  start: 2023-08-04
  end: 2023-08-27
  launch: 2023-06-08 09:00 # In UTC, but will render wrong in the text as a result... 
  launch_offset: 01:00:00 # ... So add an hour offset. site.dates are in site.timezone (UTC), so offset to the timezone the user expects (in our case, BST)

earliest_time: 2023-08-01 10:00 
latest_time: 2023-08-01 23:00 

edfringe_available: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

strict_front_matter: true 
livereload: true 

plugins:
  - bootstrap 
  - jekyll-datapage-generator

sass:
    sass_dir: _sass
    style: expanded 
    load_paths:
      - _sass 
      - vendor/bundle/ruby/*/gems/bootstrap*/assets/stylesheets/ # GitHub Pages/Action 
      - /opt/build/cache/bundle/ruby/*/gems/bootstrap*/assets/stylesheets/ #Netlify 

collections:
  content:
    output: true
    permalink: :path/
  events:
    output: true 
    permalink: :collection/:slug/ 
permalink: pretty 

defaults:
  # Defaults for pages
  - scope:
      type: content
    values:
      layout: default
  - scope: 
      type: events
    values:
      layout: events 

page_gen-dirs: true

page_gen:
  - data: 'shows.shows'
    template: 'show' 
    name: 'title'  
    dir: 'programme' 
  - data: 'shows.shows'
    template: 'show_redirect'
    name: 'title'
    dir: '/' 