backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'static'
collections:
  - name: 'pages'
    label: 'Pages'
    folder: '_content/'
    create: false 
    editor:
      preview: false 
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'age-ratings'
    label: 'Age Ratings'
    editor:
      preview: false 
    files:
      - label: 'Age Ratings'
        name: 'age-ratings'
        file: '_data/age-ratings.yml'
        fields:
          - label: 'Age Ratings'
            name: 'ratings'
            widget: 'list'
            field: {label: rating, name: rating, widget: string, summary: '{{field.rating}}'}
  - name: 'events'
    label: 'Secret Event Pages'
    editor: 
      preview: false 
    folder: '_events'
    create: true 
    fields:
      - { label: 'Title', name: 'title', widget: 'string', hint: 'Show title - must match exactly to a show' }
      - { label: 'Event Code', name: 'slug', widget: 'string', hint: 'Event code - must match exactly to the show event code. Any string. Will be used to generate the URL' }
      - { label: 'Body', name: 'body', widget: 'text', required: false, hint: 'Page body - you can put anything in here - words, links, embeds all welcome.' }
  - name: 'shows'
    label: 'Shows'
    editor:
      preview: false
    files:
      - label: '2023'
        name: '2023'
        file: '_data/shows.yaml'
        fields:
          - label: 'Shows'
            name: 'shows'
            widget: 'list'
            fields:
              - widget: string
                name: title
                label: Title
                hint: The show title
              - widget: string
                name: company
                label: Company
                required: false
                hint: The company bringing the show (may be just the writer or lead artist in some cases)
              - name: is_draft
                widget: boolean
                label: Draft
                hint: Tick to hide the show from public listings (the show page will still be generated, just not linked to from anywhere)
              - name: event_code 
                widget: string 
                required: false 
                hint: Event Code - used for secret ticket-holders-only events pages 
                label: 'Event Code (super secret)'
              - name: redirect_from
                widget: list
                required: false
                label: Redirect from 
                hint: Add a link (eg /show-name-with-typo/) to redirect from to this show
              - name: venue
                widget: select
                options: ["ZOO Southside", "ZOO Playground", "ZOO TV"]
                label: Venue
                hint: 'Which Zoo building is the show in? '
              - widget: string
                name: start_time
                required: false 
                label: Start Time
                hint: When does the performance start? In 24hr time with a colon, ie. 14:15 (Assumes all performances will start at the same time)
              - widget: string
                name: duration
                required: false
                label: Duration
                hint: How long is the performance? Use mins __or__ hours, eg. 45mins; 1hr45
              - widget: select
                name: performances
                required: false
                label: Performance Dates
                hint: Select all the performance dates for the show.
                multiple: true 
                options: ["2023-08-01","2023-08-02","2023-08-03","2023-08-04","2023-08-05","2023-08-06","2023-08-07","2023-08-08","2023-08-09","2023-08-10","2023-08-11","2023-08-12","2023-08-13","2023-08-14","2023-08-15","2023-08-16","2023-08-17","2023-08-18","2023-08-19","2023-08-20","2023-08-21","2023-08-22","2023-08-23","2023-08-24","2023-08-25","2023-08-26","2023-08-27","2023-08-28","2023-08-29","2023-08-30","2023-08-31"]
              - widget: object
                name: price
                label: Pricing
                required: false
                fields:
                  - widget: number
                    name: standard
                    label: Standard
                    required: false
                    value_type: "float" 
                    hint: Just the number, no currency please.
                  - widget: number
                    name: concession
                    required: false
                    value_type: "float" 
                    label: Concession
                    hint: "(Optional) Just the number, no currency please."
                  - widget: number
                    name: weekend
                    required: false
                    value_type: "float" 
                    label: Friday-Sunday pricing
                    hint: "(Optional) Just the number, no currency please."
                  - widget: number
                    name: weekend_conc
                    required: false
                    value_type: "float" 
                    label: Friday-Sunday concession pricing 
                    hint: "(Optional) Just the number, no currency please."
                  - widget: number
                    name: preview
                    label: Preview
                    required: false
                    value_type: "float" 
                    hint: "(Optional) Just the number, no currency please."
                  - name: price_range
                    widget: string
                    required: false
                    label: Price Range
                    hint: If prices vary, give a range here, eg. "£4 - 14". You can also
                      use words, but keep deal info (eg. BOGOF, weekend) to the ticket deals field.
                  - name: ticket_deals
                    widget: list
                    label: Ticket Deals
                    required: false
                    hint: Any ticket deals this show has, eg BOGOF, half price hut, etc. Separate each deal with a comma.

              # - type: list
              #   name: genre
              #   label: Tags
              #   config:
              #     use_select: false
              #     source:
              #       type: documents
              #       section: ''
              #       file: _data/tags.yml

              # Relation doesn't work so using select for now
              # - name: age_guidance
              #   widget: relation
              #   collection: "age-ratings"
              #   file: "age-ratings"
              #   value_field: "ratings.*.rating" 
              #   search_fields: ["ratings.*.rating"] 
              #   display_fields: ["ratings.*.rating"]
              #   required: false
              #   label: Age Guidance
              #   hint: Age guidance for shows
              - name: age_guidance 
                widget: select 
                multiple: false 
                label: Age Guidance 
                required: false 
                options:  
                    - 0+
                    - 3+
                    - 4+
                    - 7+
                    - 8+
                    - 11+
                    - 12+
                    - 13+
                    - 14+
                    - 16+
                    - 18+
              - name: ticket_url
                widget: string
                label: Ticket URL
                hint: Link to the page to book tickets
                required: false
              - name: booking_unavailable
                widget: boolean
                default: false 
                label: Booking Unavailable
                hint: Tick if tickets are not yet on sale but you do still want the show to be listed (if you don't want it listed, use the draft toggle)
              - name: age_restricted
                widget: boolean
                label: Age Restricted
                default: false 
                hint: Tick this if the age guidance is an age restriction for the show
              - widget: select
                name: access
                label: Access Provisions
                hint: Eg. BSL, Captions
                required: false
                multiple: true
                options:
                  - bsl
                  - captions
                  - relaxed
                  - ad
              - widget: string
                name: access_details
                required: false
                label: Access Performance Details
                hint: Eg. Which performances have captions, etc.

              - widget: list
                name: content_warnings
                label: Content Warnings
                required: false
                hint: Eg. Strobe lighting, strong language. These can be filtered on the programme page.
                field: {label: warning, name: warning, widget: string, summary: '{{fields.warning}}'}
              - name: content_warning_detail
                widget: list
                required: false
                label: Content Warning Detail
                hint: Details about where the content warnings feature in the show, or
                  weirdly specific content warnings (eg. a dead pig)
              - name: image
                widget: file
                required: false
                choose_url: true 
                label: Image
                hint: Show image. Must be square. If unset, uses a placeholder.
              - name: image_alt
                widget: string
                required: false
                label: Image alt text
                hint: Textual description of the show image (if unset, it's the show title)

              - widget: list
                name: video_embeds
                label: Video Embed
                summary: '{{fields.title}}'
                fields:
                  - widget: string
                    name: title
                    label: Title
                    required: false
                    hint: 'The title of this video. Eg: "Trailer".'
                  - name: embed_code
                    widget: string
                    label: Embed Code
                    required: false
                    hint: The video embed code from Vimeo
                hint: An embedded video for the show, typically a trailer.
              - widget: list
                name: links
                label: Links
                summary: '{{fields.title}}'
                fields:
                  - widget: string
                    name: title
                    label: Title
                    required: false
                    hint: What the link should say (If it's a social media link, the icon will take precedence)
                  - widget: string
                    name: link
                    label: Link
                    required: false
                  - widget: string
                    name: platform
                    label: Platform
                    required: false
                    hint: If it's Twitter, Facebook, Instagram, YouTube, or TikTok, an icon will appear instead of the name
              - widget: list
                name: reviews
                label: Reviews
                summary: '{{fields.publisher}} - {{fields.stars}}'
                fields:
                - widget: string
                  name: Publisher
                  label: publisher
                  required: false
                  hint: 'This could be the publication or the author '
                - widget: string
                  name: quote
                  label: quote
                  required: false
                - widget: number
                  name: stars
                  label: stars
                  min: 0
                  max: 5
                  step: 0.5
                  required: false
                  value_type: "float" 
              - widget: markdown
                name: copy_short
                label: Copy (Short)
                required: false
              - widget: markdown
                name: copy_long
                label: Copy (Long)
                required: false
