name: Build to GitHub pages
on:
  # schedule:
    # - cron: '0 10 * * *'
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  workflow_dispatch:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      ### PREP ###
      - name: Checkout repo
        uses: actions/checkout@v3
        # with:
          # persist-credentials: false # needed for JamesIves/github-pages-deploy-action

      ### RUBY ###
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
      - name: Cache Ruby gems
        id: cache-gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-1-${{ hashFiles('Gemfile.lock') }}
      - name: Set deployment flag 
        run: bundle config set --local deployment 'true' 
      - name: Set Ruby gems directory
        run: bundle config path vendor/bundle
      - name: Install Ruby gems
        run: bundle install --jobs 4 --retry 3

      ### BUILD ###
      - name: Build Jekyll 
        run: JEKYLL_ENV=production bundle exec jekyll build 

      ### HTMLTEST ###
      # (This tool makes sure all the links work; may require some tweaking and is optional)
      # You may find it helpful to create a .htmltest.yml file to set a config. Go wild.
      - name: Cache htmltest files
        uses: actions/cache@v2
        with:
          path: tmp/htmltest
          key: htmltest-1
      - name: Test built site with htmltest
        uses: wjdp/htmltest-action@v0.13.0-rc1 
        continue-on-error: true
        with:
          path: _site

      ### DEPLOY ###
      - name: Publish to GH Pages 🚀
        if: ${{ github.event_name != 'pull_request' || github.event_name == 'schedule'  }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.

      ### SUCCESS ### 
